# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
  - 3.4.2

r_packages:
  - covr
  - dplyr

after_success:
  - Rscript -e 'library(covr); codecov()'
